# Generated by Django 2.2.7 on 2021-04-21 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aparser', '0002_auto_20210421_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comics',
            name='id',
        ),
        migrations.AlterField(
            model_name='comics',
            name='name',
            field=models.TextField(primary_key=True, serialize=False, verbose_name='Название'),
        ),
    ]
