# Generated by Django 3.1.6 on 2021-04-22 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aparser', '0003_auto_20210421_1942'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comics',
            options={'verbose_name': 'Комикс', 'verbose_name_plural': 'Комиксы'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='users',
            name='user_id',
            field=models.TextField(unique=True, verbose_name='ID пользователя'),
        ),
    ]
