# Generated by Django 2.2.7 on 2021-04-22 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aparser', '0005_auto_20210422_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularComics',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False, verbose_name='Название')),
                ('file_id', models.TextField(verbose_name='ID комикса')),
                ('cover_id', models.TextField(verbose_name='ID обложки комикса')),
                ('colpage_pdf', models.PositiveIntegerField(verbose_name='Количество страниц')),
                ('count_views', models.PositiveIntegerField(verbose_name='Количество просмотров')),
            ],
            options={
                'verbose_name': 'Популярный комикс',
                'verbose_name_plural': 'Популярные комиксы',
            },
        ),
    ]
